### ISSUE TITLE
Commiteth web: Add conformation when disconnecting repository

### ISSUE THREAD

**Issue by asemiankevich** [status-im/open-bounty#114]
### Description

*Type*: Bug

*Summary*: No confirmation pop up shown when disconnecting repository

#### Expected behavior
Please check Zeplin screen https://app.zeplin.io/project/59dd4d45719799b4220a2e49/screen/59df6c8ecd09f0557dc827fb

![image](https://user-images.githubusercontent.com/28752642/32219225-87bfca94-be3e-11e7-8dd7-e29eb45cd80c.png)

#### Actual behavior
I can remove repository whithout conformation pop up

### Additional Information

* Browser: Chrome

**Comment by siphiuel** [comment]
Repository-related functionality moved to GitHub App.
