### ISSUE TITLE
Commiteth Welcome page: Features link does not lead anywhere

### ISSUE THREAD

**Issue by asemiankevich** [status-im/open-bounty#136]
### Description

*Type*: Bug

*Summary*: Features link seems to be not clickable, not sure which url should be pointed to it - in case we don't have correct one - can we hide the link?

#### Actual behavior
[comment]: # (Describe what actually happened.)
![image](https://user-images.githubusercontent.com/28752642/32286942-347c44a4-bf40-11e7-974d-397e843d0f89.png)

### Additional Information

* Browser: Chrome

**Comment by arash009** [comment]
Looks like "Features" link has been removed. Closing issue.
