### ISSUE TITLE
Filtering bounties

### ISSUE THREAD

**Issue by flexsurfer** [status-im/open-bounty#146]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to be able to filter open bounties by a programming language, date, repo etc.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

**Comment by arash009** [comment]
Will include as part of https://github.com/status-im/open-bounty/issues/179

Closing as duplicate
