### ISSUE TITLE
Show number of open PRs for each issue in Bounties feed

### ISSUE THREAD

**Issue by annadanchenko** [status-im/open-bounty#154]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a user, I want to know how many PRs are already opened for an issue so that  I can decide if it makes sense to contribute one more. For example, if there are already 5 open PRs it might be a waste of time to submit 6th.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: Some visual element that shows number of open PRs for each issue in the Bounties feed. When we have filtering - being able to filter by this number (issues with 0 PRs, issues with PRs < n)

**Comment by tpatja** [comment]
Good idea. Mockup would be helpful.

**Comment by tpatja** [comment]
Done. Feedback on styling needed, here is a screenshot of what it looks like now:

![open_claims_label](https://user-images.githubusercontent.com/1180880/32546514-10d71cf2-c488-11e7-8cdd-64174008daf4.png)

**Comment by denis-sharypin** [comment]
@tpatja Thanks!  Only thing what we need here to make `padding-left: 15px;` for `.open-claims-label `
