### ISSUE TITLE
Simplify our add repo view with GH app add repo event

### ISSUE THREAD

**Issue by oskarth** [status-im/open-bounty#159]
### User Story

As an org user, I want to add repos in one place (GH app) without having to do the same thing in a custom UI (ours).

### Description

*Type*: Feature

*Summary*:
(1) Listen to GH app repo events  (webhook-app route) and add to DB if user is whitelisted
(2) Replace repo view with a list of all installed repositories, or alternatively tab remove it all together.
(3) Additionally, reduce capabilities for OAuth login to only require `user:email` (no write to public repo)

Complexity if bounty: 3/5

**Comment by tpatja** [comment]
Good idea. One thing "enable repo" currently does though is create the bounty tag. We'll need some other place for doing that (could be done when receiving first webhook payload for a repo?)

**Comment by oskarth** [comment]
Good point re create bounty tag, I believe this can be done on first webhook payload but we need to check, also see exactly what permissions are needed for this.

**Comment by arash009** [comment]
Been advised that this is resolved and can be closed.
