### ISSUE TITLE
Use coinmarketcap.com API instead of cryptonator

### ISSUE THREAD

**Issue by tpatja** [status-im/open-bounty#171]
We are currently using Cryptonator's API for getting USD values for tokens and ETH. The values returned (at least for SNT) have not been very accurate, so we should switch to coinmarketcap's API.

Price data in JSON is available at `https://api.coinmarketcap.com/v1/ticker/<symbol>/`, where `<symbol>` is a name, like `status`. This means we'll need to have a mapping from TLA (eg. `SNT`) to symbol somewhere.

**Comment by tpatja** [comment]
Cryptocompare API is also on option (status-react uses it).

**Comment by arash009** [comment]
Can we confirm this has been implemented?

**Comment by tanyavariel** [comment]
Does anyone know of another that provides an API for cryptonight coins... looking specifically for TRTL - Turtlecoin.  Thanks!
