### ISSUE TITLE
Unable to update Ethereum address in Payment details.

### ISSUE THREAD

**Issue by santegoeds** [status-im/open-bounty#175]
### User Story

As a user, I created a new open-bounty account and tried to update my payment details.

### Description

*Type*: Bug

*Summary*: Using Chrome I was unable to update the Ethereum address because the browser showed a dropdown with an existing address.  Using Firefox it worked as expected.

#### Expected behavior

The page shows me an text field where I can paste my Ethereum address.

#### Actual behavior

The page shows a dropdown menu with an existing address as the available option.

### Reproduction

- Open Status
- Sign In
- Select "My Payment Details" from the account dropdown menu.
- Try to enter a new Ethereum address.

### Additional Information

* Browser: Google Chrome Version 62.0.3202.94 (Official Build) (64-bit)
* Operating System: Windows 10

![image](https://user-images.githubusercontent.com/45137/33423139-43a2967a-d5b8-11e7-9595-c4385445b1d0.png)

**Comment by andytudhope** [comment]
Hey @santegoeds. Thanks for filing this. Are you sure you didn't have a MetaMask or Parity extension operating when in Chrome? If you did, that text field will automatically pick it up. The way around this is to open in an incognito tab, or disable the relevant plugin.

**Comment by santegoeds** [comment]
Duh - you are correct.  I do have MetaMask but had no idea it prefilled addresses like this.

Thank you and apologies for the noise.
