### ISSUE TITLE
Current open claim shown against each bounty

### ISSUE THREAD

**Issue by arash009** [status-im/open-bounty#180]
@arash009 commented on [Tue Nov 28 2017](https://github.com/status-im/ideas/issues/49)

## Preamble

    Idea: #49
    Title: Current open claim shown against each bounty
    Status: Draft
    Created: 2017-11-28

## Summary
The current "Activity" tab is confusing and feels disconnected and disjointed from the "Open Bounties". These should be integrated somehow so you can track activity against each Bounty and be able to easy follow its progress.

## Vision
As a developer looking for bounties to work on, I want to have a uniform view of all bounties, both current and closed, so that I can monitor activity against them, and look at historical bounties for comparison.

As a developer working on a current bounty, I want to easily track its progress, so I can see if anyone else is also working on it or submitted a claim, and any changes to the bounty though out its life, including increase in value.

## Swarm Participants

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- UX (if relevant): 

## Requirements
Integration of the activity feed into the bounties. This may also mean we need a way to capture and display closed bounties

### Minimum Viable Product

Goal Date:  
Description: 

### Iteration 1..N
Goal Date:  
Description: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by arash009** [comment]
relates to #218 as well

**Comment by denis-sharypin** [comment]
@arash009 Please have a look,
I merged activity feed with bounties list and adapted activity copy for a context (removed bounties names, values etc ) 

![new activity](https://user-images.githubusercontent.com/6559881/35304683-af6ed748-0096-11e8-91e2-be1f3d64c811.png)

**Comment by arash009** [comment]
hmm interesting. how do you see further details back (full history) rather just the last status update? Maybe we could have a hidden list that contains the full history that gets displayed when you expand it?

**Comment by pablodip** [comment]
To me the last status update in the list might be confusing. Agree with having a hidden box that expands on demand to see the full history. Otherwise it might be worth to have the dedicated page for each bounty so that we can have the full history there.

To me we've also lost valuable information from the list: the number of open claims.

**Comment by denis-sharypin** [comment]
What's the purpose of those statuses? From my point of view, they should save time/clicks while our user choosing a right task.  As Pablo mentioned the most valuable information: is anyone submitted a claim for this task or isn't. 
I'm not sure that we need to show a full history because we have GitHub for this.

**Comment by arash009** [comment]
As discussed, to limit to only display the open claims and not the full history for this.

**Comment by denis-sharypin** [comment]
I think we reached an agreement on this design.
Link to production file in Zeplin https://zpl.io/V0Ml9AR

![submitted claims and bouties](https://user-images.githubusercontent.com/6559881/35610480-b6094f18-0661-11e8-9d1c-c24e1a8195ab.png)

**Comment by arash009** [comment]
To clarify, I believe agreement was to have the current "# of claims" still displayed next to the value, and in addition have the additional information below the bounty. This can be the MVP as displayed details of the PRs in a popup or expanded list can be complicated.

**Comment by pablodip** [comment]
@arash009 I think that is right.

The expanded list shouldn't be that complicated, I will give it a try and if it takes long I will set it as a bounty.

But I think there is a final step in design left: the list of bounties with "# of claims", where one of the bounties has open the expanded list. And I think that we talked that each bit of that info be in a list instead of a line. @denis-sharypin Could you please have a look at that?

**Comment by pablodip** [comment]
@arash009 I am changing the issue to `designing` to wait for that last final design.

**Comment by denis-sharypin** [comment]
@arash009 @pablodip 
What do you think about this design? When you click on **# of claims** it opens a small area where we show userpicks (clickable, goes to a personal profile on GitHub), name of PR and timestamp. If you click one more time on  **# of claims** it closes this area.
![sort-filters updates 2x copy](https://user-images.githubusercontent.com/6559881/36149729-206df02a-10c1-11e8-9350-3b50cb060a07.png)

**Comment by arash009** [comment]
@denis-sharypin I think thats great! Only two points:
1. Not sure if its obvious that **# of claims** is clickable. Can we do a little down arrow next to it or something?
2. Wouldnt the link of each one be to the PR link not the user GH profile?

**Comment by pablodip** [comment]
@denis-sharypin Definitely like it more than the previous one. :))

I have one point:

3.) How is it perceived that those pull requests are from the one above and not below? This might be related with 1.) than mentioned @arash009 We could have two kind of arrows, one for when it is hidden, and one for when it is expanded, and both 1.) and 3.) would probably be solved.

@arash009 

2.) I think that the links are to the PRs, but just the photo of the author of the PRs are shown there as well.

**Comment by denis-sharypin** [comment]
@pablodip @arash009 UPD
![sort-filters updates 2x copy](https://user-images.githubusercontent.com/6559881/36165598-636719a4-10f0-11e8-9f1a-c7eaffff829f.png)

**Comment by pablodip** [comment]
@denis-sharypin Like it more! I would try it like that. Let's see what @arash009 says.

**Comment by arash009** [comment]
Perfecto! Lets do it.

**Comment by denis-sharypin** [comment]
Mockup is here — https://zpl.io/2GzzP8d

**Comment by pablodip** [comment]
Nice! Just moved to `To Develop`.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xdf1bc2e001c596ce91d407574d51dc2c6206578be677e4e343f34e60398c4506](https://etherscan.io/tx/0xdf1bc2e001c596ce91d407574d51dc2c6206578be677e4e343f34e60398c4506)

**Comment by rcullito** [comment]
@denis-sharypin hello! I was looking into this task but it looks like the final link from zeplin is password protected. Just wanted to check to see if the design changed at all from the last dropdown you posted as an image?

**Comment by denis-sharypin** [comment]
@rcullito Hi!
Not there were no changes since last time. If you provide me your email address I could send you an invite to check Zeplen mockups

**Comment by rcullito** [comment]
Oh that would be great, thanks Denis. My email is rob.culliton@gmail.com

**Comment by denis-sharypin** [comment]
@rcullito Invite was sent and a link should work for you now. Please, check it. Thank you!

**Comment by rcullito** [comment]
@denis-sharypin yes that's great! I received the link and am able to explore the project in Zeplin. Thanks for your help.

**Comment by rcullito** [comment]
@denis-sharypin I was curious if the asset for the blue dropdown arrow exists in zeplin or some such similar place? thanks!

**Comment by denis-sharypin** [comment]
@rcullito Hey, here it is:
![shape-blue](https://user-images.githubusercontent.com/6559881/37549585-35bcb00e-29b4-11e8-94a1-da03f7aac987.png)
![shape-white](https://user-images.githubusercontent.com/6559881/37549586-3604b548-29b4-11e8-86a7-7e409792f701.png)

**Comment by rcullito** [comment]
awesome, thanks @denis-sharypin
