### ISSUE TITLE
Updated SOB landing page

### ISSUE THREAD

**Issue by arash009** [status-im/open-bounty#183]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As a developer coming to the Open Bounty site for the first time, I want to see some simple to understand content about what open bounty is and how it will help me so that I have enough information in the first 30 seconds to want to know more and get excited about the prospect of being paid for my open source contributions.

As an organisation coming to the Open Bounty site for the first time, I want to see some simple to understand content about what open bounty is and how it will help my organisation find talent that can help me solve my problems so that I have enough information in the first 30 seconds to want to know more and get excited about the prospect of using its service.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: The current SOB landing page provides very little information to a developer or organisation about what it is and how it works. Someone that is familiar in the space might be able to understand it, however to attract new talent and traditional organisations, we need a little more easy to consume details.

### Solution
[comment]: # (Please summarise the solution and provide a task list on what needs to be fixed.)
*Summary*:

- Add a "How it works" section that has very simple graphics and text for developers (e.g upwork.com)
- Add a "How it works" section that has very simple graphics and text for organisation
- Should have a quick 60 second video
- Our big announcement about "$1M Bounty fund for open source projects" should be presented alot bigger and more exciting.

**Comment by arash009** [comment]
Feedback from @andmironov 

In my opinion the main source of problems is not having the the bounty list itself on the homepage. It might be the best way to target both audiences (even though completely different). Show don’t tell, remember? :slightly_smiling_face:
*For Devs* it would provide a clear overview of how much money they could earn, what types of tasks there are.
*For Organizations* it would demonstrate what kind of issues can potentially be bountified, show how much money they should invest, which companies are already participating.

The bounty list itself is the most powerful way to demonstrate the features and motivate both audiences. 

Obviously i am not saying that there has to be just the bounty list on the page, but i guess it should be there, maybe after a short intro in the above-the fold

Refs: https://www.airbnb.com/ https://www.etsy.com/

**Comment by arash009** [comment]
[Homepage (general intro + bounty list)]
     -> [Specific intro + signup for Devs]
     -> [Specific intro + signup for Orgs]

**Comment by arash009** [comment]
![sob_landing_draft_7_devs](https://user-images.githubusercontent.com/33149995/35334617-1ae8ff78-0167-11e8-8871-5a82d76ca9c2.png)

**Comment by martinklepsch** [comment]
I started working on this today. @arash009 can you put me in touch with the designer who created the mockup? Would like to discuss a couple of things, discuss how to best collaborate in the future.

**Comment by arash009** [comment]
@nikitalukianov can you please work with @martinklepsch on this.

**Comment by nikitalukianov** [comment]
@martinklepsch yeah, i can help you, of course

**Comment by martinklepsch** [comment]
@nikitalukianov can we maybe chat some time tomorrow (Monday)? Book a slot here: https://calendly.com/martinklepsch/60min-ea/02-19-2018 or just send me an invite. Thanks!

**Comment by rcullito** [comment]
seems like the redesign effort has migrated away from this specific issue number. so closing for now!
