### ISSUE TITLE
Contract address is not deployed on issues with "bounty" label

### ISSUE THREAD

**Issue by churik** [status-im/open-bounty#184]
### Description

*Type*: Bug
*Summary*: 
after you add "bounty" label, SOB bot is freezing in "Deploying contract" state.
When you tap on Transaction, after redirecting to https://etherscan.io  you receive Sorry, We are unable to locate the Transaction Hash in Transaction Information

#### Expected behavior
contract is deployed

#### Actual behavior
contract is not deployed, "Sorry, We are unable to locate the Transaction Hash" in https://etherscan.io

### Reproduction

- Open issue
- add bounty label
- pay attention to SOB comment

### Additional Information
It is reproduced on issues:
https://github.com/status-im/status-react/issues/2613
https://github.com/status-im/status-react/issues/2620 (here SOB comment and bounty label will be removed)

Is not reproducible in current version on SOB test site.

* Browser: Chrome
* Operating System: Mac OSx

**Comment by arash009** [comment]
Do we still need to keep this open since this was related to the gas price issue?

**Comment by Chu127001** [comment]
Caused by ethereum network

**Comment by churik** [comment]
Caused by ethereum network
