### ISSUE TITLE
Metamask address is not updated automatically in Payment Details

### ISSUE THREAD

**Issue by churik** [status-im/open-bounty#187]
### Description

*Type*: Bug

*Summary*: 
when you setup Metamask, unlock it with your browser, login to SOB and go "My payment details" you see new address from MetaMask, but it is not really updated UNTIL you click update manually.
For you it looks like new address, but in database old address remains.

#### Expected behavior
address is updated in database (new address from MetaMask is set)

#### Actual behavior
address is updated on SOB but remains old (or empty, if it is first time) in DB
Only after you click UPDATE on SOB > Payment Details, it will be updated in DB

### Reproduction

- Open SOB
- Log in with user who set address manually or with new user
- Connect MetaMask for first time
- Go to "Payment Details"

**Comment by churik** [comment]
## 1. Address is reset in "Payment details" after page reload (if set with MetaMask)
Steps:

 - open https://openbounty.status.im:444/app
 - log in
 - log in to Metamask
 - select address from drop down
 - click on Update
 - reload page
 
### Actual result:
"Select address" is displayed

### Expected result: 
new address (same as in database)

Video: http://take.ms/9rMqd
OS: Mac OSx
Browser: Chrome

**Comment by siphiuel** [comment]
Created a PR with a fix for this: https://github.com/status-im/open-bounty/pull/263

**Comment by pablodip** [comment]
@siphiuel Where is the current pull request of this issue? :S

**Comment by siphiuel** [comment]
This would be #263.
