### ISSUE TITLE
Hide myself from scoreboard and activity

### ISSUE THREAD

**Issue by dottedmag** [status-im/open-bounty#193]
### User Story

As a user of Open Bounty, I want to be able to hide/disguise myself in the scoreboard and activity lists.

### Description

*Type*: Feature

*Summary*: People who earn cryptocurrency become more likely targets of targeted attacks. Recent claims list and "Top Hunters" list is a ready-to-use instrument for selecting people to be attacked.

#### Expected behavior

My earnings from Open Bounty system are in top 19, and I have recently submitted claims / claimed bounties.

My name and avatar are disguised in the "Top Hunters" list and "Activity" stream if I chose to do so in preferences.

#### Actual behavior

My name and avatar are posted in the "Top Hunters" and "Activity" lists.

### Reproduction

- Submit a claim / earn money via Open Bounty
- See yourself in "Activity" list
- Earn enough money to end up in Top 19.
- See yourself in "Top hunters" list.

### Solution

*Summary*:

- [ ] Add a preference to disguise myself in the public lists.

**Comment by arash009** [comment]
Thanks for requesting this @dottedmag - It would be a good feature to have. We'll add this to our backlog of items to add to a user's dashboard/profile that we want to put together.

**Comment by dottedmag** [comment]
I don't mind working on it (and another Clojure-related tasks) if you put a bounty on them.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa63893e381c0b065f43d4ff823b33aff4457b79ec800ac4264b7115b63ccf3c9](https://etherscan.io/tx/0xa63893e381c0b065f43d4ff823b33aff4457b79ec800ac4264b7115b63ccf3c9)
