### ISSUE TITLE
Metrics report on usage of SOB

### ISSUE THREAD

**Issue by arash009** [status-im/open-bounty#211]
### User Story

As the Open Bounty administrator, I want a report containing some metrics and information on the usage of SOB, so that I can make informed decisions on its development and progress.

### Description
*Type*: Feature

We need a way to capture data on use of SOB without maintaining a manual spreadsheet. This is information already contained in the DB, just needs to be exported and view built over it.

MVP can be an extract into a spreadsheet.

Data to include.
* Organisation
* Repo
* GH Issue title
* GH Issue number
* GH Issue URL
* Bounty value/token
* Bounty status (Open, Claimed, Fulfilled, Refunded) etc

Relates to #178

**Comment by rcullito** [comment]
@arash009 it looks like this has grown into your more recently updated document here: https://github.com/status-im/ideas/blob/master/ideas/122-sob-metrics.md

going to close this out to try and rein in the issue count unless you are still getting value from it?
