### ISSUE TITLE
Determine git workflow

### ISSUE THREAD

**Issue by pablodip** [status-im/open-bounty#212]
### Description

Currently master has more commits than develop, which means than changes have gone to master without passing through develop, and that develop isn't up to date with master.

Those two things have probably happened because of the complexity of maintaining both branches (explained later). The point is that those two things complicate collaboration and stability, because other collaborators can't review what is directly committed into master (production).

Having both master and develop makes sense when working with releases. But that workflow comes with a cost: maintenance complexity and slower flow of changes into production.

The develop branch is just a buffer to group changes, which are moved together into master. It represents the workflow of a release: it groups changes, and those changes are released from time to time.

Two more examples of things that are more difficult with both master and develop:

* Priority in changes: if you have some changes buffered in develop and you want to put something into production before those buffered changes, you need to either change directly master (which is described above) or merge the buffered changes with the new change (and the buffered changes might not be well tested yet, so this is bad for stability).
* Agility in the decision of changes: if you have some changes buffered in develop and you want to delay one, or to make only one, you need to separate that change from develop, since it is mixed with other changes.

The SOB doesn't have releases, but it is just a production environment (master). So I think that we are paying a cost that we don't need to.

I think the SOB fits better for a continuous delivery environment, that is, once things are ready and tested, they go directly to production. That way we wouldn't have all issues described above.

### User Stories

As a developer I want to be able to review commits before they go to production, so that I want all changes be made through pull requests.

As a developer I want to have as less workflow complexity as possible, so that I want pull requests be merged directly into master.

As a product manager I want to have a simple and powerful flow to production so that I can work better with the needs of the product.

### Proposed Changes

* Protect the master branch on Github: https://help.github.com/articles/configuring-protected-branches/

* Make pull requests pointing to master directly, and stop using the develop branch.

* Make master the default branch on Github: https://help.github.com/articles/setting-the-default-branch/.

**Comment by tpatja** [comment]
I disagree with the proposition of just using `master`. Like the README says, currently we have two continuously deployed environments - `develop` is auto-deployed to the shared test environment where we do QA and only when QA passes we merge to `master` after which the changes end up in production. The problem with just using `master` is that even if we review the changes, there is no easy way to test them. The shared test environment solves this, QA team currently does manual testing there and is working on automated tests.

`develop` is the default branch, because were getting PR's based against master. Also, `master` is already a protected branch.

**Comment by pablodip** [comment]
@tpatja 

Do you mean that the main reason right now to have the develop branch is to have a test environment for QA? If so, how about trying to find a better solution to be able to test pull requests so that we can get rid of the develop branch and solve the problems described in this issue?

A simple solution could be to have an environment where the branch to be deployed can be specified, so that the QA can deploy the pull request to test. That way isolated pull requests could be tested, even without the need to group them in a branch.

Btw, how are commits getting master without pull requests if master is protected? :S

**Comment by tpatja** [comment]
Yes, if we had an automated deploy of the PR code to a newly created environment, we could QA there and use just `master`. I also agree that this would simplify the workflow. It's not trivial to create the infrastructure for this, but we should aim to get it done.

GH [protected branches](https://help.github.com/articles/about-protected-branches/) protect against force push, not pushing commits without PR.

**Comment by pablodip** [comment]
@tpatja 

What deployment system is used right now? Can the branch be specified somehow manually? If so, could it work even if we can only have one PR deployed at a time? That is in the end what we have right now.

Regarding commits directly on master, will open an issue so that we can discuss that separately. :)

**Comment by rcullito** [comment]
Closing this out as there doesn't seem to be any current issues w/ git usage in SOB repo over the last couple of months.

Current workflow seems to be captured accurately in the project board here: https://github.com/status-im/open-bounty/projects
