### ISSUE TITLE
Ethereum workflow documentation

### ISSUE THREAD

**Issue by pablodip** [status-im/open-bounty#215]
### Description

It would be very helpful to have some docs explaining the Ethereum workflow of the Status Open Bounty.

It would also be nice to document possible malfunction/errors in that Ethereum workflow so that the Clojure system can work better against them.

### User Stories

As a clojure dev/contributor of the SOB I want to know the Ethereum workflow of the SOB so that I can understand better the whole SOB and work better and sooner with it.

As a user of the SOB I want to know the Ethereum workflow of the SOB so that I understand what it actually does in Ethereum.

### Expected Behaviour

Some docs in the README.

### Actual Behaviour

No docs about this.

**Comment by 3esmit** [comment]
Currently it uses Consensys Multisig enhanced with support to withdraw all tokens and ether with a single call. 
When SOB deploys, it uses SOB address + repository owner addess as owners of MultiSigWallet. 
SOB service waits for issue being closed by a pull request and then signs a call to withdrawAll(address) to address to issue solver. 
Then repository owner needs to sign a call to confirm(uint) to confirm the withdrawAll(address) called by SOB.

Of course, the addresses of repo owner and issue solver of need to be correctly set in the SOB service.

This will be changed in future.

**Comment by pablodip** [comment]
@3esmit Thanks! :)

Is there anything that could go badly in the process that the Clojure system should try to handle/retry/monitor/report/anything? For example, pending transactions?

> This will be changed in future.

What changes are planned? :)

**Comment by rcullito** [comment]
Closing this for now as it seems docs have landed here: https://github.com/status-im/open-bounty/tree/develop/doc

Correct me if anything here is still in flight, just trying to do some issue cleanup.
