### ISSUE TITLE
Track progress of bounty

### ISSUE THREAD

**Issue by arash009** [status-im/open-bounty#218]
### User Story

As an Organisation or repo admin user of SOB, I want to easily be able to track the progress of my bounties and what stage of the 'bounty lifecycle' its at, so I can identify whats going on with the bounty and resolve any issues if there are any.

### Description
*Type*: Feature

Currently its very hard to know what stage a bounty is up to in its lifecycle. We have an activity tab that tells you whats happened, and the SOB bot that tracks the status, but its not very visible or show history and next steps, and/or issues. These also dont reflect in different areas of SOB that could be helpful to see (e.g. repo admin cant approve payout due to eth address missing).

We should have a visual tool to show the full lifecycle of a bounty and what stage it is currently at. E.g.

1. Bounty contract executed
1. Funds added
1. PR submitted but not merged
1. PR merged
1. Check bounty hunter has active address
1. Awaiting repo admin sign off
1. Bounty awarded

In addition each step might hit roadblocks which should be highlighted.

**Comment by pablodip** [comment]
What do you have in mind about that visual tool? I think we could just integrate this info in the webapp. Right now we don't have a page for a bounty, but we could well have it and put the activity/history/events of a bounty there.

**Comment by denis-sharypin** [comment]
yeah, agree that we need to create a bounty page where we could show everything that happened with bounty. I'll prepare some mocks to discuss

**Comment by denis-sharypin** [comment]
@arash009 Hey, my thoughts on this:
Do you think the user story is correct? As a far as I get it, you want to know on what stage an issue is because you are the admin of SOB. Are those bounty statuses important for our users? We can create an admin mode where you will be able to see this and take actions

**Comment by arash009** [comment]
hmmm good point @denis-sharypin . I think this is more relevant to the repo admin/maintainer, so not SOB admin. I think some of the stages would be relevant for users, and more details based on items in the current activity feed. Maybe this could form part of the Org dashboard #178

**Comment by pablodip** [comment]
What statuses might not be relevant to users? Personally as a user I would value to see as much information as possible, since that means transparency.

By the way, from the list of statuses in the issue point 4 and 5 are probably the same, aren't they?

**Comment by denis-sharypin** [comment]
I think we should retarget current Activity tab to repos/org admins and add there all those statuses that were mentioned in the first comment.
