### ISSUE TITLE
UX details in pagination

### ISSUE THREAD

**Issue by pablodip** [status-im/open-bounty#226]
- [ ] The cursor in the buttons should be a pointer.
- [ ] When moving to a different page the screen should probably be moved to the top of the list.
- [ ] The button of next and previous page should probably look disabled when the current page is the first and the last one respectively.
- [ ] When changing the tab from bounties to activity and viceversa the current page should probably be restarted, that is, always be 1, and right now it is maintained from previous state.
- [ ] The activity list should also probably show at the top the message "Showing X of X".
- [ ] It would probably help to have some style changes when hovering paging buttons.
- [ ] On Safari and FF clicking on page number redirects to random place on page.
Video: https://drive.google.com/open?id=1ZAHPgvmb1C7tuQmYR9-kx_hPVyHRjDc4
- [ ] Pagination should work on mobile, since right now the design is broken.

cc @denis-sharypin @siphiuel

**Comment by pablodip** [comment]
Just added `On Safari and FF clicking on page number redirects to random place on page.
Video: https://drive.google.com/open?id=1ZAHPgvmb1C7tuQmYR9-kx_hPVyHRjDc4` as @churik suggested here: https://github.com/status-im/open-bounty/issues/156#issuecomment-359356610

**Comment by siphiuel** [comment]
All clear to me, except for 2 items:

1. The activity list should also probably show at the top the message "Showing X of X".
@denis-sharypin Can you please throw together some quick mockup on how it should look like? Or is it ok to proceed with a simple label on top? I only saw the mockup for Bounty list, not for Activities. Or maybe I overlooked it somewhere?
2. It would probably help to have some style changes when hovering paging buttons.
What exactly should happen there with regards to styling?

Thanks!

**Comment by pablodip** [comment]
@denis-sharypin Happy to leave that out, just removed it from the list. :)

**Comment by pablodip** [comment]
Just added a new one: `Pagination should work on mobile, since now it is broken.`.

**Comment by siphiuel** [comment]
Pushed fixes for items #1-5, 7. Changed the design of Activities page so that it is the same as Bounties. Please let me know if it's ok or not.

**Comment by siphiuel** [comment]
Also applied CSS media queries for item 8 - `Pagination should work on mobile, since right now the design is broken`.
