### ISSUE TITLE
Pending deployment in local environment

### ISSUE THREAD

**Issue by pablodip** [status-im/open-bounty#233]
When creating a bounty, it keeps telling `pending deployment`. It does send a transaction though: https://ropsten.etherscan.io/tx/0xf51e1093da3cb2f9f74bf07c6f9c3aee3818c2e77279e032a9dfede7df58eec8

This is a block in the workflow of the system in the local environment.

As far as I know it is happening to me, @siphiuel and @dmitryn.

**Comment by oskarth** [comment]
Marking as high-priority since without this it is hard for devs to actually test stuff. Part of hand-over.

@tpatja

**Comment by siphiuel** [comment]
Resolved in #244.

**Comment by pablodip** [comment]
@siphiuel Nice! So closing this one. :)
