### ISSUE TITLE
Documentation for fixing repos in strange state

### ISSUE THREAD

**Issue by andytudhope** [status-im/open-bounty#248]
Previously, we have had some repos get into strange states that required some manual work in the DB in order to fix (ref: an Aragon repo that continuously fired calls that cost a fair bit of gas).

I would love to be able to look into this myself and fix, as well as understand more clearly which kinds of states repos can get into in the first place.

**Comment by pablodip** [comment]
@andytudhope Can you remember those strange states?

I remember two:

* When the repo was renamed.
* When the permissions in the Github App changed, we didn't notice in the SOB, and things weren't working.

**Comment by andytudhope** [comment]
Yeah, those were exactly the 2 instances I was involved with - no others afaik 👍

**Comment by pablodip** [comment]
I am closing this one since we already know how to handle these issues:

The first one just by changing the info directly in the database.

And the second one by asking to enable permissions for the repo in the Github App.
