### ISSUE TITLE
Separate web and worker processes and perform graceful shutdown

### ISSUE THREAD

**Issue by pablodip** [status-im/open-bounty#258]
### User Story

As a devops I want to run the web and worker processes separately, for example in different servers, so that the server processing public web requests isn't interfered by the server processing background tasks.

As a devops I want that the processes shut down gracefully when I send them a `SIGTERM` signal, so that I can start/restart/stop them at will.

### Description

Right now there app is run through `java -jar commiteth.jar` (generated by `lein uberjar`, which in turn runs `commiteth.core/main`, which starts two main processes, the http web server for public requests and the scheduler for processing tasks.

The expected behaviour is to be able to run those processes separately like this:

• `java -jar commiteth.jar web`: only runs the http web server
• `java -jar commiteth.jar worker` only runs the scheduler

And the current behaviour should be kept as well, that is, running `java -jar commiteth.jar` with no args and starting both kind of processes.

Also each of those processes should be listening for a `SIGTERM` signal, and as soon as it is received it should finish whatever it is being done, not do anything else, and stop the process.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x5226025c514cf9c911ac898b60e07e497c4cfdf6f41a86dcbe52c06aecc7f4f4](https://etherscan.io/tx/0x5226025c514cf9c911ac898b60e07e497c4cfdf6f41a86dcbe52c06aecc7f4f4)

**Comment by virneo** [comment]
I can take this.

**Comment by andytudhope** [comment]
Closing this issue because it is stale and out-of-date.
