### ISSUE TITLE
UI filtering/sorting issues (WINDOWS)

### ISSUE THREAD

**Issue by churik** [status-im/open-bounty#262]
### User Story

As a user I want to see filters look alike in all common browsers like Chrome, Safari, Firefox, IE 11, Edge

### Description
*Type*: Bug
*Summary*: 

#### Expected behavior
1,2) scroll bar appears only in 'Owner' filter, when it is needed (>10 values)
![right_3](https://user-images.githubusercontent.com/4557972/35977770-a499e86e-0cec-11e8-9bb9-74b10256b815.png)

3) arrow in ''Sorting looks like:
![right_1](https://user-images.githubusercontent.com/4557972/35977782-aa9a053c-0cec-11e8-950f-67c5af476bcf.png)

#### Actual behavior
1) scroll bars appear in every filter
![chrome_2](https://user-images.githubusercontent.com/4557972/35977367-a14eb924-0ceb-11e8-8b48-6029749dcfc6.png) - currently presented in **IE 11, Edge, Chrome**

2) 'Value' filter is unusable in **IE 11, Edge**
![ie_11](https://user-images.githubusercontent.com/4557972/35977437-d1792d6e-0ceb-11e8-8beb-c90dc15a364a.png)
![edge_2](https://user-images.githubusercontent.com/4557972/35977446-d4918190-0ceb-11e8-953b-cf8181ba9241.png)

3) missed design for 'Sorting' arrow in  **IE11**
![ie_11_3](https://user-images.githubusercontent.com/4557972/35977576-2de15efa-0cec-11e8-9bca-d7a063e0c471.png)

### Reproduction

- Open openbounty.status.im:444/app
- Pay attention to filter\sorting view

### Solution
*Summary*:

- [ ] Fix 'Value' filter for IE 11 and Edge
- [x]  Remove unusable scrollbars
- [x] Fix 'Sorting' dropdown arrow for IE 11

### Additional Information
* Browser: IE 11, Chrome, Edge
* Operating System: **WIN 10 home edition**

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xafad3cc8e22ebe9cbadd76f1f2693446a9934d32a1b6c595bc34f95d2c798fcd](https://etherscan.io/tx/0xafad3cc8e22ebe9cbadd76f1f2693446a9934d32a1b6c595bc34f95d2c798fcd)
