### ISSUE TITLE
Footer is not pinned to the bottom

### ISSUE THREAD

**Issue by churik** [status-im/open-bounty#268]
### Description
*Type*: Bug
*Summary*: footer should be pinned to the page bottom, so I expect that no gap is shown between page bottom and footer.

#### Expected behavior
pinned footer

#### Actual behavior
a gap between footer and page bottom on some pages (which contains not a lot of content, i.e. one field)  
<img width="1482" alt="1056-842" src="https://user-images.githubusercontent.com/4557972/36031693-48f9f2a6-0db4-11e8-89ce-843a7f5c94fd.png">

### Reproduction

- Open https://openbounty.status.im:444/app
- Log in
- Tap on Profile > My payment options

### Additional Information
* Browser: Chrome, Safari 
* Operating System: OSx
* Display: 15,4-inch (2880 x 1800)

It should work with the main operating systems (Windows, Linux and Mac) and the main browsers (Chrome, Firefox, IE and Safari)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xb6faf80188cd3504ba878920a253e48e8dffd63ac0cc46853e5440d4e40b7770](https://etherscan.io/tx/0xb6faf80188cd3504ba878920a253e48e8dffd63ac0cc46853e5440d4e40b7770)

**Comment by shadywallas** [comment]
i fixed it but not able to see how to support it , pull request ?

**Comment by pablodip** [comment]
@shadywallas Yeah, you can send a pull request. There is already one (https://github.com/status-im/open-bounty/pull/270), but feel free to send a new one if you have a better solution. If so, please provide an explanation about why it is better.
