### ISSUE TITLE
Filter by currency use 'AND' instead of 'OR'

### ISSUE THREAD

**Issue by churik** [status-im/open-bounty#275]
### Description
As it turned out, most of users expect that filter by currency will use 'AND' instead of 'OR'

#### Expected behavior
'ETH' and 'SNT' enabled return all bounties with 'ETH', 'SNT' or with both of them

#### Actual behavior
'ETH' and 'SNT' enabled return only bounties with both 'ETH' and 'SNT'
![ethsnt](https://user-images.githubusercontent.com/4557972/36140777-25c8cf9c-10ab-11e8-8fb0-d130e7f84cca.png)

### Reproduction

- Open Status
- tap on 'Currency'
- Tick 'ETH' and 'SNT' 

### Additional Information

* Browser: Chrome
* Operating System: Mac OS

**Comment by pablodip** [comment]
Pending: https://github.com/status-im/open-bounty/pull/279#issuecomment-365966407

**Comment by churik** [comment]
### Environments:
* macOS HighSierra 10.13, Chrome  64
* macOS HighSierra 10.13, Safari  11
* macOS HighSierra 10.13, FireFox  58
### Tested functionality: 
verified that issue is not reproducible
### Regression: 
checked combination with 'Value', 'Owner' filter
