### ISSUE TITLE
Replace cljsjs.moment with goog.date helpers 

### ISSUE THREAD

**Issue by martinklepsch** [status-im/open-bounty#278]
### User Story

As a user, I want to OpenBounty to load and run fast so that I can get things done.

### Description

*Type*: TechDebt

*Summary*: Currently we depend on `cljsjs.moment` for a single function:

```clj
;; commiteth/common.cljs
(defn moment-timestamp [time]
  (let [now (.now js/Date.)
        js-time (clj->js time)]
    (.to (js/moment.utc) js-time)))
```

Moment.js adds ~20k (gzipped) to the build which impacts download and JS parsing time. Using `goog.date` we are able to achieve the same while also benefitting from advanced compilation strategies such as dead code elimination. I expect that with `goog.date` we might end up with this function not taking more than 1kb. 

[goog.i18n.DateTimeFormat](https://google.github.io/closure-library/api/goog.i18n.DateTimeFormat.html) might be all that's needed here.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x0a84d9d343954a8e8fa1660bef7f1fddc0e00783de20a063a1a97abaed4f4df6](https://etherscan.io/tx/0x0a84d9d343954a8e8fa1660bef7f1fddc0e00783de20a063a1a97abaed4f4df6)
