### ISSUE TITLE
Bounty revocation: UI + backend

### ISSUE THREAD

**Issue by siphiuel** [status-im/open-bounty#284]
*Type*: Feature

### Description
Currently, bounties cannot be revoked and funds cannot be withdrawn from bounties assigned to issues that are no longer considered to be up for a bounty.

Therefore, it would be nice to be able to remove GitHub bot comment and withdraw funds from associated contract if an issue had a `bounty` label removed. Thus revoked bounties should be somehow visible in SOB UI.

### Solution
On the UI side, add a section named "Revoked Bounties" to the "Manage Payouts" screen. On the backend, extend #235 with the revocation logic, as currently #235 will only remove bounties when there are no contract funds. This means that once a `bounty` label has been removed, contract funds will be withdrawn to the repo owner's address.

**Comment by pablodip** [comment]
The title of the issue only mentions UI, and the description also backend and new logic. How about splitting those in different issues?

Regarding the UI, it should probably be defined and design with @arash009 and @denis-sharypin, shouldn't it?

**Comment by pablodip** [comment]
I didn't mean to fix the title. :)) But to split the issues so that we can treat them better separately, since even though they are about revocation, they are different things.

For example we need to talk to @3esmit and @andytudhope about what we talked in point 3.) in issue #234.

And with @arash009 and @denis-sharypin the UI thing.

**Comment by siphiuel** [comment]
I think it's fine to keep it as a single issue. It can implement some basic UI, and then as suggested earlier we can improve UI separately. Having some kind of UI in the basic package will also simplify testing I guess. Just my thoughts.

**Comment by pablodip** [comment]
1.) How are revoked issues shown right now in the UI? Or not shown at all?
2.) How are revokes issues marked in the database/domain right now?

**Comment by siphiuel** [comment]
1) Not shown at all
2) If/when #235 is merged, then revoked issues will reside in the `archive` table

**Comment by martinklepsch** [comment]
Important part of this would also be cleaning up production data. :+1:

**Comment by rcullito** [comment]
relevant context here: https://github.com/status-im/open-bounty/issues/234
