### ISSUE TITLE
Require GPG signature (PR check)

### ISSUE THREAD

**Issue by martinklepsch** [status-im/open-bounty#285]
Currently there's a GitHub check that commits have a GPG signature. 
For users who don't have GPG signing set up one of the checks will fail.

While I believe that GPG signing is generally a nice thing we should also consider new contributors who might open PRs without being aware that GPG signing is mandatory. Immediately "red-flagging" their contribution due to the lack of a GPG signature might not be the most welcoming thing.

Following proposal:

- We encourage core devs to set up GPG
- We don't enforce it as part of PR checks

Some [background on what GPG signing is about](https://security.stackexchange.com/questions/120706/why-would-i-sign-my-git-commits-with-a-gpg-key-when-i-already-use-an-ssh-key-to).

**Comment by pablodip** [comment]
What is the exact advantage of requiring it to core devs and not to external contributors?

That post talks mainly about tags, but we don't use tags. :S

**Comment by martinklepsch** [comment]
> What is the exact advantage of requiring it to core devs and not to external contributors?

Signing commits allows others to verify that a commit has been created by you. In theory someone might get ahold of your GitHub account and publish commits under your name. GPG signing is an additional layer to prevent that.

Requiring it from core-devs only would seem appropriate since core-devs might push code directly or their code is reviewed with a less critical eye than the code of an external contributor. It shouldn't be that way of course but still. Also I assume we want to keep the barrier-to-entry as low as possible.

I don't have strong opinions whether we enforce GPG signing or not. I think it is nice but it obviously also creates some friction. 

One thing I have a strong opinion about is that we should make a call here and adjust our PR checks accordingly. Currently [most open PRs](https://github.com/status-im/open-bounty/pulls) have red cross marks either due to actual problems or GPG signing. This makes it harder to see what state a PR is in and if it might be ready for merging. 

I'll try to get ahold of someone who can let us know if this is company policy or not.

**Comment by pablodip** [comment]
Yeah, can't see a concrete benefit from GPG right now. :S

Totally agree with adjusting the status checks to only the ones that we use.  So for me we can just disable the GPG for now. Do you know how that can be done?

**Comment by martinklepsch** [comment]
Well the concrete benefit is that we can verify that a commit has been made by one of us 🙂 

There's some more context around GPG signing and why it has been adopted for `status-react`: https://wiki.status.im/Code_signing_commits_into_develop — I'm currently trying to figure out if it is company policy or not. 

Given that the effort to set up GPG isn't terribly high I'm close to suggesting we just do it. It seems like a good general practice to me to use whatever we have available to verify authenticity of commits.

**Comment by martinklepsch** [comment]
So as per https://status-im.slack.com/archives/C962N8HJ5/p1518695704000167 GPG signing is currently soft-enforced. I'd suggest that everyone sets up GPG signing as it will become an enforced policy at some point. 

Are you ok with that? @churik @siphiuel @pablodip

**Comment by martinklepsch** [comment]
FWIW here's a very minimal starting point to get GPG signing set up on OS X:

1. install https://gpgtools.org/
2. generate a keypair
3. upload public key to github
4. put this into your gitconfig:

       [commit]
           gpgsign = true

**Comment by pablodip** [comment]
Couldn't still find a plain example of the risk and explanation of the solution, but I'm okay with using it. :)

How are we going to deal with external contributors in the end? The status check is still there. :S

**Comment by martinklepsch** [comment]
@pablodip as far as I understood the status check is only done on commits of core contributors (I assume GitHub organization members are considered that).

The risk: 
- Some attacker gets access to my GitHub account. 
- They may then add commits and tags to the repository. 
- Without GPG signing we have no way to verify if the commit/tag has actually been created by me.

The solution: 
- I share my public PGP key somewhere.
- I use my private key to "sign" the commit. 

Now you can verify that the commit or tag has been authored by me and not an attacker who may have gotten access to my GitHub account.

I hope this makes some sense. Thanks for being ok with using it. Maybe in a few days those PR states will actually be useful again 🙂

**Comment by pablodip** [comment]
The weird thing is that we are protecting what is already a disaster: account access. And we can try with GPG, but in other platforms we would already be lost, like in a server provider account or so. And we're protecting the Github account with the same ways as other accounts, hehe.

And also: if an attacker can access our Github, can't they also change the GPG keys and sign well too? Don't totally get that. :S

And also: if I use the attacker uses the Github editor, I think that Github automatically verifies those commits.

I just have some gaps in my understanding. :S

**Comment by siphiuel** [comment]
1. I don't completely understand the rationale either
2. But am fine with using it. I've already had gpg setup before
3. If you're using macOS and console gnupg/pinentry (e.g. installed via `brew install gnupg`), please just don't forget to add `export GPG_TTY=$(tty)` to your shell config. Otherwise `git commit` will hang.

**Comment by dmitryn** [comment]
>And also: if an attacker can access our Github, can't they also change the GPG keys and sign well too? Don't totally get that. :S

@pablodip you can upload your gpg public key somewhere like https://keybase.io/trybeee as Martin said. This way you can verify committer is the person he really claims to be .

**Comment by martinklepsch** [comment]
@dmitryn thanks for chiming in! @pablodip you are correct — if we only rely on GitHub to provide the GPG public key then this doesn't add much. The public key should be provided from a separate/trusted place like a personal website, keybase, etc.

**Comment by pablodip** [comment]
Thanks for that! Still some gaps, but totally okay using it, no worries. :)
