### ISSUE TITLE
Transition Wiki into doc/ directory

### ISSUE THREAD

**Issue by martinklepsch** [status-im/open-bounty#286]
As discussed in standup. Reasons mostly being that wiki might get out of sync with state of repository.

**Comment by siphiuel** [comment]
Do you think we should include https://github.com/status-im/open-bounty/wiki/Contributor-Guidelines in the repo? It does not depend on the state of repo itself.

**Comment by pablodip** [comment]
Yeah, my vote is for including everything in the repo, so that we get all the versioning and collaboration superpowers that we have round the repo.

**Comment by martinklepsch** [comment]
@siphiuel with that file specifically it might make sense to place it in the repo as `CONTRIBUTING.md` since github provides some special functionality around that.

**Comment by siphiuel** [comment]
So there it is: #287.
