### ISSUE TITLE
Derive bounty state from database

### ISSUE THREAD

**Issue by arash009** [status-im/open-bounty#300]
In order to render a list of bounties on the dashboard of people managing bounties it would be useful to define some kind of data structure that completely describes the state of a bounty and can be used for rendering.

- Derive bounty state from database
- Simple Clojure data structure
- Potentially described using clojure.spec

##### EDITS

> Added some more context. @martinklepsch

**Comment by pablodip** [comment]
What exactly is this about? :S

**Comment by martinklepsch** [comment]
@pablodip it's a result of [the meeting around org dashboard](https://docs.google.com/document/d/1PqzNR7dKUr4grU1XnC7dRQM2Uk0rSb6a1910Vph6Hbw/edit) today:

**Comment by martinklepsch** [comment]
Taking this over since @siphiuel is still busy with #235 and #303.

**Comment by martinklepsch** [comment]
```clj
(defn bounty-state [bounty]
  (cond
    (:payout_hash bounty)                :paid
    (nil? (:confirm_hash bounty))        :pending-maintainer-confirmation
    (nil? (:payout_address bounty))      :pending-contributor-address
    (:winner_login bounty)               :merged
    (some-> (:claim_count bounty) (< 1)) :multiple_claims
    (= 1 (:claim_count bounty))          :claimed
    (seq (:tokens bounty))               :funded
    (:contract_address bounty)           :opened))
```
