### ISSUE TITLE
Dashboard reports - basic 

### ISSUE THREAD

**Issue by arash009** [status-im/open-bounty#301]
### User Story

As a repo maintainer using Open Bounty, I was to see some simple metrics and reports on number of bounties and costs, so I can manage my finances

*Type*: Feature

Simple report showing values of:
1. Total bounties assigned + combined value
1. Total bounties paid out + combined value

---
##### EDITS
> Deleted "graph over time" as I think we agreed not to make that part of initial build.   
> @martinklepsch

**Comment by martinklepsch** [comment]
test
