### ISSUE TITLE
Remove web3-externs.js

### ISSUE THREAD

**Issue by martinklepsch** [status-im/open-bounty#304]
We currently have a file [`externs/web3-externs.js`](https://github.com/status-im/open-bounty/blob/develop/externs/web3-externs.js) which contains some externs for web3.js. 

Improvements to the ClojureScript compiler probably allow us to get rid of that file and utilize [externs inference](https://clojurescript.org/guides/externs) instead. 

It might also be that we don't need those externs at all since we depend on [cljs-web3](https://github.com/district0x/cljs-web3) which in turn depends on [cljsjs/web3](https://github.com/cljsjs/packages/tree/master/web3) which should already provide some externs.

#### Acceptance Criteria

- [ ] verify if the externs are actually needed (remove them, see if related functionality breaks)
- [ ] if they are needed replace them with type-hints as described in the [ClojureScript Externs documentation](https://clojurescript.org/guides/externs)
- [ ] verify that related functionality still works

@andytudhope requesting bounty for this. S or M, not sure. @pablodip @siphiuel

**Comment by pablodip** [comment]
I personally don't agree with using the inference system of externs because it is still Alpha and doesn't totally eliminate the biggest pain of externs: different behaviour in dev and prod, which produces a lot of pain.

My vote is to use something like this: https://github.com/binaryage/cljs-oops, with the motivation explained here: https://github.com/binaryage/cljs-oops#motivation

**Comment by pablodip** [comment]
Btw, not sure if we should put bounties that might not be possible, and we know it in advance. What happens for the contributors if it is true that it isn't possible to complete the issue?

**Comment by martinklepsch** [comment]
Externs inference is here to stay and I’m not sure how warranted the existence of the Alpha label is at this point. 

For the minimal amount of externs we have right now extern inference seems like an appropriate tool compared to introducing a specialized library.

Also consider that by using a non-Standard library here the codebase becomes harder to understand for new contributors who are not familiar with cljs-oops.

This is not to say that we shouldn’t consider cljs-oops at all, just that it is not part of this issue. This issue is about cleaning up some small bits of code and removing an unnecessary top level directory from the repository. 

The outcomes of this issue can be different based on whatever the contributor finds out (I.e. do we still need that file at all?) but that is something different than the issue not being solvable at all.

**Comment by pablodip** [comment]
> For the minimal amount of externs we have right now extern inference seems like an appropriate tool compared to introducing a specialized library.

We don't use a specialised library, just `goog.object` for now.

As I told you the externs strategy has a huge problem that it would be nice if we can just avoid it.

> The outcomes of this issue can be different based on whatever the contributor finds out (I.e. do we still need that file at all?) but that is something different than the issue not being solvable at all.

What solvable situations do we have? Is it totally possible to get rid of `web3-externs.js`? Why the` if possible` then? I think that is is very helpful to define a concrete goal for the pain that we want to solve with the issue, and the rest just notes or ideas.

**Comment by martinklepsch** [comment]
> We don't need to use a specialised library, just `goog.object` for now.

I misunderstood you then, I thought you wanted to use `cljs-oops`. I'd be fine with using `goog.object` instead of externs inference if you have strong opinions on this. FWIW the cljs-oops author states in the README that cljs-oops [was created before Externs Inference was available](https://github.com/binaryage/cljs-oops#faq) and that he considers Externs Inference a promising approach. 

> As I told you the externs strategy has a huge problem that it would be nice if we can just avoid it.

I'm well aware of externs and associated problems. I'm not sure however I'd consider them to be huge. Externs are a reliable way of supporting Foreign Function Interfacing (FFI) and it's the approach that's used inside Google and other places using the Closure compiler. Sure it introduces some development-production mismatch but so does developing with optimizations `:none`. We're past the point where we can have a completely identical setup for ClojureScript in development and production.

> What solvable situations do we have? Is it totally possible to get rid of `web3-externs.js`? Why the `if possible` then?

The `if possible` was confusing, thanks for catching that, I removed it. The concrete goal is to remove the externs file and replace it with Externs Inference. Or `goog.object` if you feel strongly about this being the superior approach.

Does that seem sensible?

**Comment by martinklepsch** [comment]
BTW, this presentation (also linked in the cljs-oops README) is pretty nice: 

- [Navigating ClojureScript Fire Swamps](https://github.com/spinningtopsofdoom/navigating-clojurescript-fire-swamp/blob/master/presentation/navigating-clojurescript-fire-swamps.pdf)

It also points out another option which is probably the ultimate end-game here: native module processing. I think this might be worth exploring later on as it allows us to remove dead code from  JavaScript dependencies. This is a bit more complex though and it remains to be seen if web3.js can even be compiled properly using the Closure compiler. Maybe @madvas has looked into this. I opened [an issue against `cljs-web3`](https://github.com/district0x/cljs-web3/issues/5) to track this.

In the meantime the benefits by cljs-oops and Externs Inference are similar. 

For the record: Proper externs have one added advantage in that they allow us to indicate if a function is side-effect free. This can improve dead code elimination. I doubt that this will have a large impact in our code base but it's an interesting difference between cljs-oops/Extern Inference and Externs files.

**Comment by pablodip** [comment]
> I'd be fine with using goog.object instead of externs inference if you have strong opinions on this.

I think it's more than a opinion, but concrete real pains:

* Potential breakages in production code, and so in production itself.
* Very frustrating bugs to fix, that require full advanced compilation for every trial and error.

> I'm well aware of externs and associated problems. I'm not sure however I'd consider them to be huge. Externs are a reliable way of supporting Foreign Function Interfacing (FFI) and it's the approach that's used inside Google and other places using the Closure compiler. Sure it introduces some development-production mismatch but so does developing with optimizations :none. We're past the point where we can have a completely identical setup for ClojureScript in development and production.

Not sure to understand the intention and expectation of this paragraph and others about externs. Is it that you prefer to use externs, are arguing for it and expect a response? Is it just an opinion with no intention and don't expect a response? I feel the conversation like a chat instead of goal-oriented. I'd appreciate to use a goal-oriented conversation as much as possible, by conveying clearly intention and expectation.

I'm totally open to alternatives to solve problems. I just think that those alternatives should be explained and argued fully (if possible not with authoritative reasons, even if they are by Google :) and compared with advantages and disadvantages to other alternatives, to see clearly the benefits an tradeoffs.

If you come up with a way of interactive with Javascript code that doesn't have the pains mentioned in this thread, I'm totally open to it.

> The if possible was confusing, thanks for catching that, I removed it. The concrete goal is to remove the externs file and replace it with Externs Inference. Or goog.object if you feel strongly about this being the superior approach.
> Does that seem sensible?

Okay, for the title, not yet the description.

Please, define the concrete goal in the description once we agree on the strategy about using Javascript code. Let's see what @siphiuel thinks as well.

**Comment by martinklepsch** [comment]
> I think it's more than a opinion, but concrete real pains:

Sorry, I wasn't intending to imply that it's "just an opinion" without arguments to back it up :) 

The pain points you mention seem to apply to extern **files** and I'd say they mostly stem from extern files being out-of-date or incomplete in other ways. Would you agree? As far as I can tell Extern Inference does not suffer from these issues? 

Also, shouldn't QA catch issues around production code? 

> Not sure to understand the intention and expectation of this paragraph and others about externs.

Point taken. I guess what I was trying to get at is that externs are part of life when compiling against Google Closure and tooling to work with them will only improve.

Here is my comparison of the four approaches we have discussed before. I hope this qualifies as "explained and argued fully". If you feel like I missed points feel free to edit this comment.

#### Extern Files
- Benefits:
  - Easily available for many libraries
- Drawbacks:
  - Need to be maintained and updated manually
  - Incomplete externs can lead to annoying to debug advanced compilation issues

#### goog.object
- Benefits:
  - Straightforward to use
  - No externs required
- Drawbacks:
  - Somewhat clumsy compared to regular interop

#### cljs-oops
- Benefits:
  - No externs required
  - additional utilities to deal with JS objects
  - perhaps less clumsy to use than `goog.object` directly
- Drawbacks:
  - Additional dependency
  - contributors need to understand `cljs-oops` before they can contribute
  - Still more clumsy than regular interop

#### Externs inference
- Benefits
  - Standard compiler tooling
  - No externs required
  - Simple annotation allows regular interop across entire project 
   `(def ^js/SomeThing thing js/Something)`
  - Tooling to detect when properties are not externed correctly 
   `(set! *warn-on-infer* true)`
- Drawbacks
  - alpha

**Comment by pablodip** [comment]
> The pain points you mention seem to apply to extern files and I'd say they mostly stem from extern files being out-of-date or incomplete in other ways. Would you agree? As far as I can tell Extern Inference does not suffer from these issues?

Externs inference just create extern files as far as I know, so they have all of the issues/drawbacks that manual externs have. The only thing that externs inference gives you as far as I know is that it writes some extern files for you. It doesn't solve the two pains that we are mentioning in the thread.

**Comment by martinklepsch** [comment]
It's true that Extern Inference generates an externs file but as I mentioned I believe the problems you described mostly stem from extern files that are maintained manually. 

> - Potential breakages in production code, and so in production itself.
> - Very frustrating bugs to fix, that require full advanced compilation for every trial and error.

Could you explain how these problems would occur if the externs file is always up to date, as it is by using Extern Inference?

**Comment by pablodip** [comment]
The problems I described can happen with any extern file, unless the extern file is perfect. And extern inference generates extern files based on the code. The code can have bugs/not enough information, so incorrect extern files can be generated. And with incorrect files we have the mentioned pain problems.

**Comment by martinklepsch** [comment]
I agree that buggy code can lead to issues — as it can with `cljs-oops`. There's no difference between development and production with regards to when stuff can break with `cljs-oops` or Extern Inference.

I'll move forward with removing the extern file as that has been the original purpose here. Looking at the code removing it should have no effect but @churik can test the relevant stuff just to be safe.
