### ISSUE TITLE
Fix :reload-all

### ISSUE THREAD

**Issue by pablodip** [status-im/open-bounty#306]
### User Story

As a developer, I want to be able to execute a `:reload-all` over any namespace so that I can get all code reloaded to that namespace reloaded.

### Description

Right now when you execute:

* `(require 'commiteth.core)` ( it works)
* `(require 'commiteth.core :reload-all)` (it breaks)

You get this exception:

```
CompilerException clojure.lang.ArityException: Wrong number of args (4) passed to: core/def-sqlvec-fns, compiling:(hugsql/core.clj:342:11) 
```
<details>
<summary>Full Stacktrace</summary>
<pre>
#error{:cause "Wrong number of args (4) passed to: core/def-sqlvec-fns",
       :via [{:type clojure.lang.Compiler$CompilerException,
              :message "clojure.lang.ArityException: Wrong number of args (4) passed to: core/def-sqlvec-fns, compiling:(hugsql/core.clj:342:11)",
              :at [clojure.lang.Compiler analyzeSeq "Compiler.java" 6875]}
             {:type clojure.lang.ArityException,
              :message "Wrong number of args (4) passed to: core/def-sqlvec-fns",
              :at [clojure.lang.Compiler macroexpand1 "Compiler.java" 6781]}],
       :trace [[clojure.lang.Compiler macroexpand1 "Compiler.java" 6781]
               [clojure.lang.Compiler analyzeSeq "Compiler.java" 6854]
               [clojure.lang.Compiler analyze "Compiler.java" 6669]
               [clojure.lang.Compiler analyze "Compiler.java" 6625]
               [clojure.lang.Compiler$BodyExpr$Parser parse "Compiler.java" 6001]
               [clojure.lang.Compiler$FnMethod parse "Compiler.java" 5380]
               [clojure.lang.Compiler$FnExpr parse "Compiler.java" 3972]
               [clojure.lang.Compiler analyzeSeq "Compiler.java" 6866]
               [clojure.lang.Compiler analyze "Compiler.java" 6669]
               [clojure.lang.Compiler analyzeSeq "Compiler.java" 6856]
               [clojure.lang.Compiler analyze "Compiler.java" 6669]
               [clojure.lang.Compiler access$300 "Compiler.java" 38]
               [clojure.lang.Compiler$DefExpr$Parser parse "Compiler.java" 589]
               [clojure.lang.Compiler analyzeSeq "Compiler.java" 6868]
               [clojure.lang.Compiler analyze "Compiler.java" 6669]
               [clojure.lang.Compiler analyze "Compiler.java" 6625]
               [clojure.lang.Compiler eval "Compiler.java" 6931]
               [clojure.lang.Compiler eval "Compiler.java" 6916]
               [clojure.lang.Compiler load "Compiler.java" 7379]
               [clojure.lang.RT loadResourceScript "RT.java" 372]
               [clojure.lang.RT loadResourceScript "RT.java" 363]
               [clojure.lang.RT load "RT.java" 453]
               [clojure.lang.RT load "RT.java" 419]
               [clojure.core$load$fn__5677 invoke "core.clj" 5893]
               [clojure.core$load invokeStatic "core.clj" 5892]
               [clojure.core$load doInvoke "core.clj" 5876]
               [clojure.lang.RestFn invoke "RestFn.java" 408]
               [clojure.core$load_one invokeStatic "core.clj" 5697]
               [clojure.core$load_one invoke "core.clj" 5692]
               [clojure.core$load_lib$fn__5626 invoke "core.clj" 5737]
               [clojure.core$load_lib invokeStatic "core.clj" 5736]
               [clojure.core$load_lib doInvoke "core.clj" 5717]
               [clojure.lang.RestFn applyTo "RestFn.java" 142]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$load_libs invokeStatic "core.clj" 5774]
               [clojure.core$load_libs doInvoke "core.clj" 5758]
               [clojure.lang.RestFn applyTo "RestFn.java" 137]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$require invokeStatic "core.clj" 5796]
               [clojure.core$require doInvoke "core.clj" 5796]
               [clojure.lang.RestFn invoke "RestFn.java" 512]
               [conman.core$eval71157$loading__5569__auto____71158 invoke "core.clj" 1]
               [conman.core$eval71157 invokeStatic "core.clj" 1]
               [conman.core$eval71157 invoke "core.clj" 1]
               [clojure.lang.Compiler eval "Compiler.java" 6927]
               [clojure.lang.Compiler eval "Compiler.java" 6916]
               [clojure.lang.Compiler load "Compiler.java" 7379]
               [clojure.lang.RT loadResourceScript "RT.java" 372]
               [clojure.lang.RT loadResourceScript "RT.java" 363]
               [clojure.lang.RT load "RT.java" 453]
               [clojure.lang.RT load "RT.java" 419]
               [clojure.core$load$fn__5677 invoke "core.clj" 5893]
               [clojure.core$load invokeStatic "core.clj" 5892]
               [clojure.core$load doInvoke "core.clj" 5876]
               [clojure.lang.RestFn invoke "RestFn.java" 408]
               [clojure.core$load_one invokeStatic "core.clj" 5697]
               [clojure.core$load_one invoke "core.clj" 5692]
               [clojure.core$load_lib$fn__5626 invoke "core.clj" 5737]
               [clojure.core$load_lib invokeStatic "core.clj" 5736]
               [clojure.core$load_lib doInvoke "core.clj" 5717]
               [clojure.lang.RestFn applyTo "RestFn.java" 142]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$load_libs invokeStatic "core.clj" 5774]
               [clojure.core$load_libs doInvoke "core.clj" 5758]
               [clojure.lang.RestFn applyTo "RestFn.java" 137]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$require invokeStatic "core.clj" 5796]
               [clojure.core$require doInvoke "core.clj" 5796]
               [clojure.lang.RestFn invoke "RestFn.java" 619]
               [commiteth.db.core$eval70664$loading__5569__auto____70665 invoke "core.clj" 1]
               [commiteth.db.core$eval70664 invokeStatic "core.clj" 1]
               [commiteth.db.core$eval70664 invoke "core.clj" 1]
               [clojure.lang.Compiler eval "Compiler.java" 6927]
               [clojure.lang.Compiler eval "Compiler.java" 6916]
               [clojure.lang.Compiler load "Compiler.java" 7379]
               [clojure.lang.RT loadResourceScript "RT.java" 372]
               [clojure.lang.RT loadResourceScript "RT.java" 363]
               [clojure.lang.RT load "RT.java" 453]
               [clojure.lang.RT load "RT.java" 419]
               [clojure.core$load$fn__5677 invoke "core.clj" 5893]
               [clojure.core$load invokeStatic "core.clj" 5892]
               [clojure.core$load doInvoke "core.clj" 5876]
               [clojure.lang.RestFn invoke "RestFn.java" 408]
               [clojure.core$load_one invokeStatic "core.clj" 5697]
               [clojure.core$load_one invoke "core.clj" 5692]
               [clojure.core$load_lib$fn__5626 invoke "core.clj" 5737]
               [clojure.core$load_lib invokeStatic "core.clj" 5736]
               [clojure.core$load_lib doInvoke "core.clj" 5717]
               [clojure.lang.RestFn applyTo "RestFn.java" 142]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$load_libs invokeStatic "core.clj" 5774]
               [clojure.core$load_libs doInvoke "core.clj" 5758]
               [clojure.lang.RestFn applyTo "RestFn.java" 137]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$require invokeStatic "core.clj" 5796]
               [clojure.core$require doInvoke "core.clj" 5796]
               [clojure.lang.RestFn invoke "RestFn.java" 436]
               [commiteth.db.users$eval70658$loading__5569__auto____70659 invoke "users.clj" 1]
               [commiteth.db.users$eval70658 invokeStatic "users.clj" 1]
               [commiteth.db.users$eval70658 invoke "users.clj" 1]
               [clojure.lang.Compiler eval "Compiler.java" 6927]
               [clojure.lang.Compiler eval "Compiler.java" 6916]
               [clojure.lang.Compiler load "Compiler.java" 7379]
               [clojure.lang.RT loadResourceScript "RT.java" 372]
               [clojure.lang.RT loadResourceScript "RT.java" 363]
               [clojure.lang.RT load "RT.java" 453]
               [clojure.lang.RT load "RT.java" 419]
               [clojure.core$load$fn__5677 invoke "core.clj" 5893]
               [clojure.core$load invokeStatic "core.clj" 5892]
               [clojure.core$load doInvoke "core.clj" 5876]
               [clojure.lang.RestFn invoke "RestFn.java" 408]
               [clojure.core$load_one invokeStatic "core.clj" 5697]
               [clojure.core$load_one invoke "core.clj" 5692]
               [clojure.core$load_lib$fn__5626 invoke "core.clj" 5737]
               [clojure.core$load_lib invokeStatic "core.clj" 5736]
               [clojure.core$load_lib doInvoke "core.clj" 5717]
               [clojure.lang.RestFn applyTo "RestFn.java" 142]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$load_libs invokeStatic "core.clj" 5774]
               [clojure.core$load_libs doInvoke "core.clj" 5758]
               [clojure.lang.RestFn applyTo "RestFn.java" 137]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$require invokeStatic "core.clj" 5796]
               [clojure.core$require doInvoke "core.clj" 5796]
               [clojure.lang.RestFn invoke "RestFn.java" 930]
               [commiteth.routes.redirect$eval70652$loading__5569__auto____70653 invoke "redirect.clj" 1]
               [commiteth.routes.redirect$eval70652 invokeStatic "redirect.clj" 1]
               [commiteth.routes.redirect$eval70652 invoke "redirect.clj" 1]
               [clojure.lang.Compiler eval "Compiler.java" 6927]
               [clojure.lang.Compiler eval "Compiler.java" 6916]
               [clojure.lang.Compiler load "Compiler.java" 7379]
               [clojure.lang.RT loadResourceScript "RT.java" 372]
               [clojure.lang.RT loadResourceScript "RT.java" 363]
               [clojure.lang.RT load "RT.java" 453]
               [clojure.lang.RT load "RT.java" 419]
               [clojure.core$load$fn__5677 invoke "core.clj" 5893]
               [clojure.core$load invokeStatic "core.clj" 5892]
               [clojure.core$load doInvoke "core.clj" 5876]
               [clojure.lang.RestFn invoke "RestFn.java" 408]
               [clojure.core$load_one invokeStatic "core.clj" 5697]
               [clojure.core$load_one invoke "core.clj" 5692]
               [clojure.core$load_lib$fn__5626 invoke "core.clj" 5737]
               [clojure.core$load_lib invokeStatic "core.clj" 5736]
               [clojure.core$load_lib doInvoke "core.clj" 5717]
               [clojure.lang.RestFn applyTo "RestFn.java" 142]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$load_libs invokeStatic "core.clj" 5774]
               [clojure.core$load_libs doInvoke "core.clj" 5758]
               [clojure.lang.RestFn applyTo "RestFn.java" 137]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$require invokeStatic "core.clj" 5796]
               [clojure.core$require doInvoke "core.clj" 5796]
               [clojure.lang.RestFn invoke "RestFn.java" 1289]
               [commiteth.handler$eval60994$loading__5569__auto____60995 invoke "handler.clj" 1]
               [commiteth.handler$eval60994 invokeStatic "handler.clj" 1]
               [commiteth.handler$eval60994 invoke "handler.clj" 1]
               [clojure.lang.Compiler eval "Compiler.java" 6927]
               [clojure.lang.Compiler eval "Compiler.java" 6916]
               [clojure.lang.Compiler load "Compiler.java" 7379]
               [clojure.lang.RT loadResourceScript "RT.java" 372]
               [clojure.lang.RT loadResourceScript "RT.java" 363]
               [clojure.lang.RT load "RT.java" 453]
               [clojure.lang.RT load "RT.java" 419]
               [clojure.core$load$fn__5677 invoke "core.clj" 5893]
               [clojure.core$load invokeStatic "core.clj" 5892]
               [clojure.core$load doInvoke "core.clj" 5876]
               [clojure.lang.RestFn invoke "RestFn.java" 408]
               [clojure.core$load_one invokeStatic "core.clj" 5697]
               [clojure.core$load_one invoke "core.clj" 5692]
               [clojure.core$load_lib$fn__5626 invoke "core.clj" 5737]
               [clojure.core$load_lib invokeStatic "core.clj" 5736]
               [clojure.core$load_lib doInvoke "core.clj" 5717]
               [clojure.lang.RestFn applyTo "RestFn.java" 142]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$load_libs invokeStatic "core.clj" 5774]
               [clojure.core$load_libs doInvoke "core.clj" 5758]
               [clojure.lang.RestFn applyTo "RestFn.java" 137]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$require invokeStatic "core.clj" 5796]
               [clojure.core$require doInvoke "core.clj" 5796]
               [clojure.lang.RestFn invoke "RestFn.java" 805]
               [commiteth.core$eval60988$loading__5569__auto____60989 invoke "core.clj" 1]
               [commiteth.core$eval60988 invokeStatic "core.clj" 1]
               [commiteth.core$eval60988 invoke "core.clj" 1]
               [clojure.lang.Compiler eval "Compiler.java" 6927]
               [clojure.lang.Compiler eval "Compiler.java" 6916]
               [clojure.lang.Compiler load "Compiler.java" 7379]
               [clojure.lang.RT loadResourceScript "RT.java" 372]
               [clojure.lang.RT loadResourceScript "RT.java" 363]
               [clojure.lang.RT load "RT.java" 453]
               [clojure.lang.RT load "RT.java" 419]
               [clojure.core$load$fn__5677 invoke "core.clj" 5893]
               [clojure.core$load invokeStatic "core.clj" 5892]
               [clojure.core$load doInvoke "core.clj" 5876]
               [clojure.lang.RestFn invoke "RestFn.java" 408]
               [clojure.core$load_one invokeStatic "core.clj" 5697]
               [clojure.core$load_all$fn__5618$fn__5621 invoke "core.clj" 5713]
               [clojure.core$load_all$fn__5618 invoke "core.clj" 5713]
               [clojure.lang.AFn call "AFn.java" 18]
               [clojure.lang.LockingTransaction run "LockingTransaction.java" 273]
               [clojure.lang.LockingTransaction runInTransaction "LockingTransaction.java" 229]
               [clojure.core$load_all invokeStatic "core.clj" 5711]
               [clojure.core$load_all invoke "core.clj" 5705]
               [clojure.core$load_lib$fn__5626 invoke "core.clj" 5737]
               [clojure.core$load_lib invokeStatic "core.clj" 5736]
               [clojure.core$load_lib doInvoke "core.clj" 5717]
               [clojure.lang.RestFn applyTo "RestFn.java" 142]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$load_libs invokeStatic "core.clj" 5774]
               [clojure.core$load_libs doInvoke "core.clj" 5758]
               [clojure.lang.RestFn applyTo "RestFn.java" 137]
               [clojure.core$apply invokeStatic "core.clj" 648]
               [clojure.core$require invokeStatic "core.clj" 5796]
               [clojure.core$require doInvoke "core.clj" 5796]
               [clojure.lang.RestFn invoke "RestFn.java" 421]
               [user$eval60984 invokeStatic "form-init8069671980921109939.clj" 1]
               [user$eval60984 invoke "form-init8069671980921109939.clj" 1]
               [clojure.lang.Compiler eval "Compiler.java" 6927]
               [clojure.lang.Compiler eval "Compiler.java" 6890]
               [clojure.core$eval invokeStatic "core.clj" 3105]
               [clojure.core$eval invoke "core.clj" 3101]
               [clojure.main$repl$read_eval_print__7408$fn__7411 invoke "main.clj" 240]
               [clojure.main$repl$read_eval_print__7408 invoke "main.clj" 240]
               [clojure.main$repl$fn__7417 invoke "main.clj" 258]
               [clojure.main$repl invokeStatic "main.clj" 258]
               [clojure.main$repl doInvoke "main.clj" 174]
               [clojure.lang.RestFn invoke "RestFn.java" 1523]
               [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__25412 invoke "interruptible_eval.clj" 87]
               [clojure.lang.AFn applyToHelper "AFn.java" 152]
               [clojure.lang.AFn applyTo "AFn.java" 144]
               [clojure.core$apply invokeStatic "core.clj" 646]
               [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1881]
               [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1881]
               [clojure.lang.RestFn invoke "RestFn.java" 425]
               [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invokeStatic "interruptible_eval.clj" 85]
               [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 55]
               [clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__25457$fn__25460
                invoke
                "interruptible_eval.clj"
                222]
               [clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__25452
                invoke
                "interruptible_eval.clj"
                190]
               [clojure.lang.AFn run "AFn.java" 22]
               [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
               [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
               [java.lang.Thread run "Thread.java" 745]]}
</pre>
</details>

**Comment by martinklepsch** [comment]
@pablodip good point 👍The full stacktrace would be useful here for documentation purposes.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x7cfd35894770d42cef045f8fe4afe26735b936809db8d1b73dc55d0a9a7859b1](https://etherscan.io/tx/0x7cfd35894770d42cef045f8fe4afe26735b936809db8d1b73dc55d0a9a7859b1)
