### ISSUE TITLE
Fix Develop

### ISSUE THREAD

**Issue by pablodip** [status-im/open-bounty#307]
I think that right now we have develop dirty with some not finished/working feature/s, so it would be nice to fix that to unblock the workflow.

@churik Could you please confirm that, and if so what feature/s or issues or pull requests?

Thanks! :)

**Comment by churik** [comment]
new PRs in develop branch:

1. #317
2. #263
3. #199
4. #289
5. #311
6. #276
7. #283
8. #279
9. #298
