### ISSUE TITLE
seed postgres with sample activity data

### ISSUE THREAD

**Issue by rcullito** [status-im/open-bounty#312]
### User Story

As a developer, when starting Open Bounty locally it would be nice to see example bounties and activity in the dashboard. 

A great deal of the core functionality within the repo is, at heart, about displaying this data in an easily understandable way. In addition to improving the developer experience, this would also be a good sanity check for examining different use cases of local changes, and spotting bugs before they get to a later stage in the QA process. 

### Description

*Type*: Feature

*Summary*:
This could take the form of a migration script that could be run simply with `lein seed` or some variant: a one off job that that is not necessarily required by the build process, but exists in the case that it offers assistance and prevents developers from reimplementing the same functionality.

**Comment by pablodip** [comment]
Just for the record, to have a correct state in the SOB system the database isn't enough, but also there is state in an Ethereum network and in Github. So having just state in the database wouldn't be a complete and correct state. But agree that it is a good first step and would help start working with the web app. :)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x823a0c9952c4ae97351153fc4f5ea786af4e32d33b1f98b2691df6b7c51af9db](https://etherscan.io/tx/0x823a0c9952c4ae97351153fc4f5ea786af4e32d33b1f98b2691df6b7c51af9db)

**Comment by rcullito** [comment]
@pablodip yes I see what you are saying! Agreed that it has to be a combination of all three (db + eth + GH) or there is very little value to the developer experience from an application perspective. Will view this as a *first step* in that light of the broader goal 🚶
