### ISSUE TITLE
Pull requests are shown as open bounties 

### ISSUE THREAD

**Issue by churik** [status-im/open-bounty#328]
### Description
*Type*: Bug
*Summary*: currently issues and pull requests with label `bounty` are shown in https://openbounty.status.im/app, but in fact only issues can be bounties

#### Expected behavior
only issues are displayed in "Open bounties" list

#### Actual behavior
issues and  pull requests  are shown as open bounties 

### Reproduction

- Open https://openbounty.status.im/app
- Click on  `[FIX #3229] Change home add button on ios to blue` (one of pull requests) in order to make sure that this is pull request with  `bounty` label

### Additional Information
* Browser: Chrome 
* Operating System: macOS HighSierra 10.13

**Comment by siphiuel** [comment]
Removed all pull requests from DB. They were mistakenly added manually when checking all whitelisted repos for issues with a `bounty` label. Search was done using GitHub API, and it returned pull requests together with issues.

Instead of
```clj
(search/search-issues nil {:label "bounty" :user repo-owner} params)
```

should have used this instead:
```clj
(search/search-issues nil {:label "bounty" :user repo-owner :type "issue"} params)
```

**Comment by churik** [comment]
New PRs with `bounty` labels are not displayed in staging env.
