### ISSUE TITLE
Bounties are updated randomly and several times per event

### ISSUE THREAD

**Issue by churik** [status-im/open-bounty#346]
### Description

*Type*: Bug
*Summary*: some bounties are updated randomly, so displayed as top items on `Open Bounties`

#### Expected behavior
bounties are updated only when balance is changed, winner is set, ect, so once per event

#### Actual behavior
GitHub comments on some issues are updated from time to time and displayed as top items(
<img width="947" alt="issue" src="https://user-images.githubusercontent.com/4557972/36975048-7f602114-2081-11e8-9524-0860559c8be8.png">

### Reproduction

- Open https://openbounty.status.im/app
- Click on any bounty
- Navigate to status-open-bounty bot comment
- Check editing hitory

### Additional information
* Browser: Chrome
* Operating System: Mac OS High Sierra

**Comment by siphiuel** [comment]
Addressed with #350.
