### ISSUE TITLE
Do not invoke GitHub API update operations needlessly

### ISSUE THREAD

**Issue by siphiuel** [status-im/open-bounty#385]
### Description

*Type*: Bug
GitHub comments should only be updated once after any relevant input changes.

#### Expected behavior
GitHub comment is not updated unless:
  - there is a change in the state of a bounty or associated contract (bounty contract mined, waiting for confirmation, paid, etc.)
  - contributor's payout address is not set
  - ETH or token balance changes

#### Actual behavior
If a PR for an issue with a bounty has been merged, but the contributor has no Ethereum address set in OpenBounty, scheduler's `self-sign-bounty` thread will attempt to repeatedly update a GitHub comment with text "Pending user to save ETH address", although just one update is enough.

#### Steps to reproduce
  - Register a contributor's account on SOB
  - Do not set Ethereum account address for contributor
  - Create an issue with a bounty from an owner's account
  - Post and merge a PR from that contributor's account
  - Check that OpenBounty bot comment is being updated each minute with the same text "Pending user to save ETH address"

### Solution
Store an additional flag inside issue comment hash (`comment_hash` field in `issue_comment` table). Currently the hash is generated based on a tuple `owner, repo, issue_number, eth_balance`. Include an additional flag from the enumeration `address_not_set, pending_confirmation, paid`. Always generate a hash based on this data before posting a GitHub comment update and proceed only if generated hash differs from the one stored in database.

**Comment by martinklepsch** [comment]
@arash009 did we get an update from GitHub whether our changes have already reduced the issue sufficiently?

**Comment by arash009** [comment]
The main concern at the time was that one issue that was doing the non-stop repeated calls which we stopped straight away. That was confirmed.

Once this is implemented we will go back to them to recheck our usage.
