### ISSUE TITLE
 rebuild header component using tachyons

### ISSUE THREAD

**Issue by rcullito** [status-im/open-bounty#396]
### Description

The SOB team is moving towards [Tachyons](https://tachyons.io/) for sensible css without lighting our hair on fire. The header component could benefit from integration with this library. 

An example of how SOB is using Tachyons thus far can be found on this PR: https://github.com/status-im/open-bounty/pull/392

**Comment by martinklepsch** [comment]
FYI I’m planning to write up a Decision Record regarding Tachyons as part of the work on #392.

**Comment by martinklepsch** [comment]
This should also address https://github.com/status-im/open-bounty/issues/377

**Comment by EugeOrtiz** [comment]
Also #410 please.
