### ISSUE TITLE
[End-to-end tests] Implement bounty funding

### ISSUE THREAD

**Issue by churik** [status-im/open-bounty#398]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

*Summary*: to test full process of claiming/closing bounties we need to implement contract funding for [end-to-end tests](https://github.com/status-im/open-bounty/tree/develop/test/end-to-end).
You can find full installation and configuration manual: [SOB end-to-end tests](https://wiki.status.im/Status_Open_Bounty_end-to-end_tests)

So for it, we require separate methods for:
* grabbing contract address
* sending transaction (STT tokens) using [MyEtherWallet](https://www.myetherwallet.com/#send-transaction) or any suitable API 

**Preferrable way to implement features by is by using GitHub API and Go Ethereum API**, so less interaction with UI.

### Solution

- [ ] Implement function for grabbing contract address 
*Location:* [github.py](https://github.com/status-im/open-bounty/blob/develop/test/end-to-end/pages/thirdparty/github.py)
*Description:* in order to have contract address for particular bounty we need to grab it from SOB bot comment in  [bounty](https://github.com/NewOrGanizationSOB/RepoSOB/issues/145).
#### Get contract address 
Params: `issue_link`
Actions:
***Preferrable: to use [GitHub API](https://developer.github.com/v3/) to read SOB bot comment and grab address from it***
OR grab address from GitHub interface, to do this:
* find SOB bot comment by the locator 
* Grab and return text with contract address
![monosnap 2018-04-11 11-40-07](https://user-images.githubusercontent.com/4557972/38605865-2fe43a44-3d7d-11e8-83be-2a7238298e66.png)

Return value: `contract_address`
 
- [ ] implement methods for transferring funds
*Location:* new class in [thirdparty](https://github.com/status-im/open-bounty/tree/develop/test/end-to-end/pages/thirdparty)
*Description:* there should be the simple way to fund bounties in STT (Status Test Tokens). 
***Preferrable: to use [A python interface for interacting with the Ethereum blockchain ](https://github.com/ethereum/web3.py) to send STT to particular address***
If there is no way how to do it with API, use Selenium with MyEthereumWallet interface(required actions are described below)

*Prerequisites:* 
* how to get STT to your metamask account - send a 0 ETH transaction with Gas Limit `105000` (it’s non default and you need to change it!) to 0x34358C45FbA99ef9b78cB501584E8cBFa6f85Cef
* How to get test ETH: use [Ropsten Faucet](http://faucet.ropsten.be:3001/)
####  Sending transactions from wallet to contract address;
Params:  `metamask_password`(in case of using MetaMask), `amount`, `contract_address`
Actions (manual way with MyEthereumWallet interface): 
* unlock MetaMask with `metamask_password`
* check that in MetaMask selected Network is Ropsten TestNet  
* open https://www.myetherwallet.com/#send-transaction 
* close popup 'If MyEtherWallet can't do those things, what's the point?'
* select MetaMask / Mist
* click `Connect to MetaMask`
* Check whether tokens are visible (`STT` presence in Token Balances block): 
   *  if not - add Custom token [How To Do it?](http://take.ms/if8Np)
       * click on  `Add custom token`
       * fill `Token Contract Address`,  `Token Symbol`, `Decimals` with info `0xc55cF4B03948D7EBc8b9E8BAD92643703811d162 `, `STT`, `18`
       * click `Save`
       * check that  STT tokens appear in the currencies dropdown (right to `Amount to send`)
* Fill `To Address` with  `contract_address`
* Fill `Amount to Send` with  `amount`
* Choose STT in dropdown
* Click on `Generate Transaction`
* Click on `Send Transaction`
* Click on `Yes, I am sure! Make a transaction`
*  Click on Submit in MetaMask Popup
Return value: `tx_hash`
![txhash](https://user-images.githubusercontent.com/4557972/38609317-67dfc36a-3d86-11e8-9af4-4e473e729f34.png)

- [ ] create a test 
*Location:* [test_contracts.py](https://github.com/status-im/open-bounty/blob/develop/test/end-to-end/tests/test_contracts.py) 
*Description:* to show up that methods are working, create a sample test for funding this [bounty](https://github.com/NewOrGanizationSOB/RepoSOB/issues/145).

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x966e053d104da6477d294be1d5eef55e817ef00ee71692163e4e04175a47b62d](https://etherscan.io/tx/0x966e053d104da6477d294be1d5eef55e817ef00ee71692163e4e04175a47b62d)

**Comment by leonprou** [comment]
Hey, is this bounty still relevant?

I tried to run the test with `python3 -m pytest -m sanity --env=local` but the fail on:

```
tests/test_contracts.py::TestLogin::test_deploy_new_contract INFO:root:Tap on LoginButton
INFO:root:Looking for EmailEditbox
INFO:root:Type myusername to EmailEditbox
INFO:root:Looking for PasswordEditbox
INFO:root:Type mypassword to PasswordEditbox
INFO:root:Tap on SignInButton
INFO:root:Looking for PermissionTypeText
ERROR
```

Seems that the test can't find the '.permission-title' selector on a github page.. Actually I can't find in either 🤔

**Comment by leonprou** [comment]
@churik hey, thanks for answering 😊 
I followed your advise and tweaked the `config.ini` a little more, now I nearly passed the first test..
I'll try to continue to go on with this soon.

But actually I think I can create the new end to end test without selenium at all.. using web3py must be much more fast.

**Comment by churik** [comment]
@leonprou go ahead!
I described just one of the possible ways (and I think not the best one), so if you can do it using web3py inside end-to-end tests - feel free to experiment.
Thanks:)

**Comment by leonprou** [comment]
@churik Ok I started working on it, the part of grabbing the contract address from link is already done. Hope you'll hear from me soon!

I'm just not sure If I need to check in the open bounties app that I started working on this.

**Comment by churik** [comment]
@leonprou do you mean to sign up to https://openbounty.status.im/?

You can do this when you want, but I suggest to do it before your PR will be merged.
All that you need to claim bounty - you can find [here](https://github.com/status-im/open-bounty/blob/develop/doc/testing.md) - section for **Bounty Hunter**

Feel free to ask any questions.

**Comment by leonprou** [comment]
@churik ok, cool.

You know I though a little about that test. You want to check that a specific bounty - https://github.com/NewOrGanizationSOB/RepoSOB1_2/issues/145 (which already deployed) can be funded.

But actually you test the same contract again and again. Even if you change your codebase this test will always work. So actually you kind of testing the Ethereum Ropsten network.  This test also problematic cause you need to always keep some ETH/SNT at your account.

This makes more sense too test the funding of the contract in a unit test, simulating the Ethereum network with something like truffle (http://truffleframework.com/). Maybe you have one already.

**Comment by churik** [comment]
@leonprou I just put as bounty actions required for real test. Of course, I haven't in mind to test Ropsten.
So after these steps will be implemented I'm going to check that values are updated everywhere - in SOB GitHub bot comment, in `Bounties` list, in `Activity` list, in `Manage bounties`.
