### ISSUE TITLE
One contract is deployed for different issues

### ISSUE THREAD

**Issue by churik** [status-im/open-bounty#399]
### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: two issues with `bounty` label have the same contract address:
https://github.com/status-im/status-react/issues/3050
https://github.com/status-im/status-react/issues/3820

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
different address on different bounties
#### Actual behavior
[comment]: # (Describe what actually happened.)
two issues have the same contract address

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
Cannot reproduce in `staging env`
Tried to put  the label `bounty` in two issues at the same time:
- directly from issue pages
- mark several in issues list and put `label`
Every time it works like expected: SOB bot handled them one by one.

**Comment by martinklepsch** [comment]
Some improved logging has been put in place which will hopefully help us understand why this is happening the next time it happens.

**Comment by martinklepsch** [comment]
Related:
- https://github.com/web3j/web3j/issues/43
- [FastRawTransactionManagrer.java](https://github.com/web3j/web3j/blob/master/core/src/main/java/org/web3j/tx/FastRawTransactionManager.java) which tracks nonces in order to be able to submit multiple transactions per block
