### ISSUE TITLE
Events landing page

### ISSUE THREAD

**Issue by arash009** [status-im/open-bounty#438]
To help support the onboarding of users that we meet at events and meetups, we need to have a specific landing page to use at these meetups that the user can sign up from and provide their information. This way, we're able to match up users that complete bounties with promotions that they 'opt-in' for.

A form similar to [this](https://docs.google.com/forms/d/e/1FAIpQLScLsFiyF8sswg5swfb9QUFZ_MTtTnKG-R1XTWNZN0gNqekO3g/viewform) that also captures the event and signs up the user to Open Bounty at the same time.

Perhaps as part of this, we also have 'promo codes' that we can give out at events, each of these providing certain incentive to the user to sign up and complete a bounty, e.g. 2x payouts.

**Comment by EugeOrtiz** [comment]
@arash009 Do you want to keep the same questions from the current form?

**Comment by EugeOrtiz** [comment]
@arash009 @rcullito 
[Desktop design @ Zeplin](http://zpl.io/VOWp3Al)
[Mobile design @ Zeplin](http://zpl.io/aRq9kXr)

Let me know if you have any comments!
