### ISSUE TITLE
Bounties show zero balance when funded with a token different to SNT, ANT, SWT or ETH

### ISSUE THREAD

**Issue by jjperezaguinaga** [status-im/open-bounty#467]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story

As an organisation, I want to fund bounty issues with my own ERC-20 tokens, so that my community gets rewarded by helping the product they support.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Bug

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: When funding a bounty with an ERC-20 token that isn't SWT, SNT, AWT or ETH, the contract isn't updated and the bounty shows up empty even though it has been funded with some tokens (e.g. MYB).

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
The bounty shows up with the right amount of tokens deposited into the bounty. E.g:
![image](https://user-images.githubusercontent.com/1128312/41716662-cc4aa108-751c-11e8-90d4-81b7712beff2.png)

#### Actual behavior
[comment]: # (Describe what actually happened.)
The bounty shows up zero balance, despite having some tokens being deposited into the bounty. E.g.:
![image](https://user-images.githubusercontent.com/1128312/41716688-e7f81840-751c-11e8-93d0-eb0a8ca27099.png)

![image](https://user-images.githubusercontent.com/1128312/41716772-29a09c9a-751d-11e8-9267-f4af7d4c2510.png)

(See [bounty](https://github.com/MyBitFoundation/mybit-issues/issues/9) and [contract address](https://etherscan.io/address/0x5d1ed8776fbf3c5fbfc9c847f8f364b5aed25270) for detailed example).

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)

- Ensure you have added the status-open-bounty-app in your Github organisation, had been whitelisted by the Status team and the label `bounty` has been created, as well as the bot actually posting a contract after you label an issue

![image](https://user-images.githubusercontent.com/1128312/41716959-c6548b1e-751d-11e8-8e50-f3d761018f27.png)

![image](https://user-images.githubusercontent.com/1128312/41716976-d3837aca-751d-11e8-8772-7871b8abc591.png)

- Fund the smart contract with any token different than SNT, ANT, SWT or ETH. In this case, we funded it with a MYB token.
- See that the balance of the contract address does not change.
- Get sad 😢 

### Additional Information

* Ethereum wallet used: Metamask and Eidoo to fund the contract. At first it was used one that wasn't the one linked to the OpenStatus website (Eidoo wallet), but afterwards it was used the one linked without result.

[comment]: # (Browser and version)
* Browser: Chrome

[comment]: # (OS version)
* Operating System: OSX

**Comment by jjperezaguinaga** [comment]
@rcullito just mentioned in the chat channel the following likely reason why the token hasn't shown up:

![image](https://user-images.githubusercontent.com/1128312/41717358-1e449ade-751f-11e8-939f-0a1f7e3def91.png)

Since the MYB token used did a token swap recently, the Parity Registry hasn't been updated.

**Comment by jjperezaguinaga** [comment]
@rcullito we finally managed to update the token registry with the new token. I think we now only need a cache refresh from your side :blush:

**Comment by rcullito** [comment]
believe we can close this down for now as we seem to be over the hurdle with the `MYB` token. from our end, we'll try and make it more explicit in our documentation that new tokens require a ping in riot to let us know. 

thanks for bringing up @jjperezaguinaga
