### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by ligi** [status-im/open-bounty#56]
These permissions are quite intrusive:

![selection_081](https://cloud.githubusercontent.com/assets/111600/25461045/0bec29e8-2ae7-11e7-908d-d1e646603d0b.png)

And I think most of them are not needed right? As far as I understand only issue read/write is used ..

**Comment by Smokyish** [comment]
Hi @ligi, have you read the April development update post yet, these permissions are quite clearly explained there: https://blog.status.im/commiteth-development-update-april-2017-b689281d2d2f

**Comment by ligi** [comment]
I was reading the post 2 times now - and I see that there is permissions mentioned and you reduced them already(thanks for this) - but still I am not sure why you need so many..

**Comment by jarradh** [comment]
Hey @ligi we'd certainly appreciate any advice to reduce them, we encountered some issues with github when we tried to.

**Comment by ligi** [comment]
Github integrations are a great way to have very fine grained permissions:

https://developer.github.com/changes/2016-09-14-Integrations-Early-Access/

**Comment by jarradh** [comment]
```
Thanks for signing!
You’ve signed the pre-release agreement for your organization @status-im.
There’s nothing more you need to do here. Make sure your primary email address is up-to-date so that we can get a hold of you. If you have any questions, let us know.
```

Yeah, great.

**Comment by ligi** [comment]
Github apps are now publicly available and I was writing a MVP for this use-case based on it - read about it here: http://walleth.org/2017/10/18/issuETH-ethereum-issue-bounties/

**Comment by jarradh** [comment]
Awesome thanks @ligi, we'll integrate it directly now that it's available. I'm curious if there was something preventing you from contributing directly to Commiteth?

**Comment by ligi** [comment]
Great! 2 things where hindering me:
 - this would change a lot - would not be a simple PR - after applying the change there would not have been much left of commiteth - using github apps is kind of a paradigm shift for the app
 - I don't like to write clojure which commiteth uses
 - Speed of movement: was just faster to do it this way ..

**Comment by arash009** [comment]
Permissions changes have been implemented. Closing as resolved.
